version: '3.8'
services:
  frontend:
    build: &node_image
      context: ./image
      dockerfile: Dockerfile 
    volumes:
      - type: bind 
        source: ./ws/frontend
        target: /home/node/ws
    ports:
      - 2525:3000
    environment:
      - SERVICE_NAME=frontend
  
  backend:
    build: *node_image
    volumes:
      - type: bind 
        source: ./ws/backend
        target: /home/node/ws
    ports:
      - 2828:3000
    environment:
      - SERVICE_NAME=backend